# Generated by Django 2.2.3 on 2019-09-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('uploader', models.CharField(blank=True, default='', max_length=100)),
                ('videoid', models.CharField(default='none', max_length=11)),
                ('description', models.CharField(default='none', max_length=800)),
                ('thumbnail', models.CharField(default='none', max_length=100)),
                ('captions', models.TextField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
